Website = "https://github.com/mrpoundsign/InkAnim"

[Details]
  Icon = "assets/icon.png"
  Name = "InkAnim"
  ID = "com.inkanim.studio"
  Version = "0.5.0-beta"
  Build = 11

[Migrations]
  fyneDo = true
